from geometric_features.aggregation.ocean.subbasin_regions import subbasins
from geometric_features.aggregation.ocean.ocean_basins import basins
from geometric_features.aggregation.ocean.antarctic_regions import antarctic
from geometric_features.aggregation.ocean.ice_shelf_regions import ice_shelves
from geometric_features.aggregation.ocean.moc_basins import moc
from geometric_features.aggregation.ocean.transport_transects import transport
