# Based on https://github.com/NOAA-ORR-ERD/gridded/blob/master/.travis.yml
# and https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/.travis.yml
# and https://github.com/MPAS-Dev/MPAS-Tools/blob/master/.travis.yml
language: minimal

sudo: false

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - name: "python3.6"
    - name: "python3.7"
    - name: "python3.8"

env:
  global:
    secure: "j+8wznD/5m7bHkxOA7Wa+c2ozxGzFDAKH2UJh6z1B5R2cjwOExganEwsEjYN6JsYNoep2Y5IKUyzyIFeICN8NkrP2xLtiCil8mYHuNNwoLSsSCuo6HidcBU7Ukx8WPiIvfC/jytYLeeoKU2Xc/8sWKq7wxIwMjBtmE1PJBtPUOzlxMtECLb1ckdyPAAlyVYxTXlbFgQ+y777glYNo/5gyiclWj2lbQ5j2GCFkIhkcfoI3IIE6HHDw9BUCiujhzwEq6f4bROIutVSs9RW/KhfvUfvOffn7AkBRQvvtz6Ru6g7YvqEG3J/ia0PGJqEBUTzQVeEGuUsNjEOHTkGlBd3aB6CEgceUBYIBxmLymKf0RycLPQV2ifwcxfQOJqXNrS2VNRIuG7RPWCwsT6z26XCMTyZx0GVN0MmFg6cjr0RKEDxJw3CehTlZnI8YYSEGKKX3sxCLdK0aL+pDlNH+uiqWaGLV/Tbaf3cniy1td/603HoRQyym1aNuuLfNjQqr/nkJBUJAaDafFXgkzCMCpLv/+VNP14b8j0WttWQphVNxxWys+r8/oqiZGFXKYmGdjn4Za0OSnwfRoN7oX8orCo/qq1YTrB5lfdU1J3f+7RvQQ/9i/vqXPl4k2FRyRlMFP505ZZ1uQiBdZagOuz3tWImMHGQGlTvZGNrkqBLNvE2WUI="

before_install:
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    source $HOME/miniconda/etc/profile.d/conda.sh
    conda activate base
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda install conda-build

install:
  - "./travis_ci/install.bash"

script:
  - "./travis_ci/test_and_publish_docs.bash"