name: geometric_features_docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytest
  - numpy
  - matplotlib
  - cartopy
  - shapely
  - requests
  - progressbar2
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - tabulate >= 0.8.2
  - m2r
